url: https://spectarun.com
baseurl:
source:      .
destination: ../spectarun.github.io-master
plugins:     ./_plugins
layouts:     ./_layouts
include:     ['.htaccess']
exclude:     []
timezone:    nil

# Site settings
title: SpectaRun Workouts
email: spectarun@gmail.com
description: "Visualize workouts from your Apple Watch on your iPhone, and export those workouts so you can upload them to your favorite online community."

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: F5003F
  secondary: F5003F
  secondary-dark: 333

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/spectarun
  - title: twitter
    url: http://twitter.com/spectarun

# Postal address (add as many lines as necessary)
address:

# Build settings
markdown: kramdown
permalink: pretty
